#SIS2406 - Estructura de Datos y Algoritmos
## Primavera 2024

<div>
<img src="https://drive.google.com/uc?export=view&id=1_ZAbL21argoGVFRpHidRYf5vOKgdusal" width="250"/>
</div>

### SIS2406_Python_1.2

**Enrique Naredo García**

<font size = 2>
©️ Todos los derechos reservados. All rights reserved.

*Nota: El presente documento es una herramienta diseñada única y exclusivamente para los estudiantes de la asignatura arriba mencionada. Se recuerda no compartir esta información fuera de los integrantes registrados en este curso. La reproducción total o parcial de este documento requiere autorización por escrito del titular del copyright.*
</font>

#1.2 Arreglos

En esta práctica se introduce los tipos de arreglos utilizados en Python.

Se utiliza Jupyter notebook para ejecutar directamente en cada celda el código generado en Python.

En cada sección se da una breve explicación y posteriormente se proporciona un ejemplo en código.

**Notas:**

* En Python el símbolo #, se utiliza para agregar un comentario (el cual no se ejecuta).
* Se recomienda realizar la práctica utilizando el lenguaje de programación correspondiente.
* Se recomienda realizar modificaciones al código para verificar y comprender de manera correcta el funcionamiento del mismo.

## Python

Python es un lenguaje interpretado, lo cual quiere decir que no se compila.

* Python ejecuta directamente el código línea por línea.
* Si existen errores en el código del programa, su ejecución se detiene.



###Proceso

1. Escribir el código en cada celda.
2. Guardar el archivo ejemplo.py en un folder
3. Ejecutarlo con la instrucción python ejemplo.py

**Notas:**

* En Google Colab los Jupyter notebooks usualmente se guardan en la siguiente ruta: /content/drive/MyDrive/Colab Notebooks/.
* En Google Colab si el archivo se guarda en el directorio: /content, entonces al momento de cerrar la sesión este archivo desaparecera.
* Si se requiere mantener los archivos, entonces se recomienda montar primero el Google drive y crear un directorio para tal fin.

##Ejemplo de Listas

Utilizando la librería estándar de Python

In [1]:
# Lista de enteros
enteros = [1, 2, 3, 4, 5]
print("Lista de enteros: ", enteros)

Lista de enteros:  [1, 2, 3, 4, 5]


In [2]:
# Lista de floats
floats = [1.1, 2.2, 3.3, 4.4, 5.5]
print("Lista de floats: ", floats)

Lista de floats:  [1.1, 2.2, 3.3, 4.4, 5.5]


In [3]:
# Lista de strings
strings = ["hola", "mundo", "de", "Python"]
print("Lista de strings: ", strings)

Lista de strings:  ['hola', 'mundo', 'de', 'Python']


In [4]:
# Lista de booleanos
booleans = [True, False, True, False, True]
print("Lista de booleanos: ", booleans)

Lista de booleanos:  [True, False, True, False, True]


In [5]:
# Lista de tuplas
tuplas = [(1, 2), (3, 4), (5, 6)]
print("Lista de tuplas: ", tuplas)

Lista de tuplas:  [(1, 2), (3, 4), (5, 6)]


In [6]:
# Lista de arreglos (listas anidadas)
arrays = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print("Lista de arreglos: ", arrays)

Lista de arreglos:  [[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [7]:
# Lista de diccionarios
diccionarios = [{"nombre": "Juan", "edad": 30}, {"nombre": "Ana", "edad": 25}]
print("Lista de diccionarios: ", diccionarios)

Lista de diccionarios:  [{'nombre': 'Juan', 'edad': 30}, {'nombre': 'Ana', 'edad': 25}]


##Tabla con métodos para Listas

Python tiene un conjunto de métodos integrados que puede usar en listas/matrices.

| Method     | Description |
| :----------| :------:    |
| append()   | Adds an element at the end of the list |
| clear()    |	Removes all the elements from the list |
| copy()     |	Returns a copy of the list |
| count()    | Returns the number of elements with the specified value |
| extend()   |	Add the elements of a list (or any iterable), to the end of the current list |
| index()    |	Returns the index of the first element with the specified value |
| insert()   |	Adds an element at the specified position |
| pop()      |	Removes the element at the specified position |
| remove()   |	Removes the first item with the specified value |
| reverse()  |	Reverses the order of the list |
| sort()     |	Sorts the list |


En Python, las listas son estructuras de datos versátil que puede utilizarse como vector o matriz.


Aquí hay algunos métodos integrados que se pueden usar en listas:

In [9]:
# Crear una lista
mi_lista = [1, 2, 3]

In [10]:
# Agregar un elemento al final de la lista
mi_lista.append(4)

# Imprime: [1, 2, 3, 4]
print(mi_lista)

[1, 2, 3, 4]


In [11]:
# Insertar un elemento en la posición 1
mi_lista.insert(1, 10)

# Imprime: [1, 10, 2, 3, 4]
print(mi_lista)

[1, 10, 2, 3, 4]


In [12]:
# Eliminar el primer elemento que tenga el valor 10
mi_lista.remove(10)

# Imprime: [1, 2, 3, 4]
print(mi_lista)

[1, 2, 3, 4]


In [13]:
# Eliminar el último elemento de la lista
mi_lista.pop()

# Imprime: [1, 2, 3]
print(mi_lista)

[1, 2, 3]


In [14]:
# Ordenar los elementos de la lista
mi_lista.sort()

# Imprime: [1, 2, 3]
print(mi_lista)

[1, 2, 3]


In [15]:
# Invertir el orden de los elementos de la lista
mi_lista.reverse()

# Imprime: [3, 2, 1]
print(mi_lista)

[3, 2, 1]


In [16]:
# Contar el número de ocurrencias del valor 2 en la lista
print(mi_lista.count(2))  # Imprime: 1

1


##Arrays

En Python, se puede utilizar el módulo array para trabajar con arrays.

* Sin embargo, para trabajar con arrays multidimensionales y obtener funcionalidades adicionales, se recomienda utilizar la biblioteca NumPy.

* Aquí hay algunos métodos integrados que se pueden usar en arrays utilizando el módulo array:

In [17]:
# Importar el módulo array
import array as arr

In [21]:
# Crear un array de enteros
mi_array = arr.array('i', [1, 2, 3, 4, 5])

In [22]:
# Imprimir el array
print(mi_array)

array('i', [1, 2, 3, 4, 5])


In [23]:
# Obtener el tipo de datos del array
print(mi_array.typecode)  # Imprime: 'i'

i


In [24]:
# Obtener el tamaño del elemento en bytes
print(mi_array.itemsize)  # Imprime: 4

4


In [25]:
# Obtener el número de elementos en el array
print(len(mi_array))  # Imprime: 5

5


In [26]:
# Agregar un elemento al final del array
mi_array.append(6)
print(mi_array)  # Imprime: array('i', [1, 2, 3, 4, 5, 6])

array('i', [1, 2, 3, 4, 5, 6])


##Librería numpy

NumPy (Numerical Python) es una biblioteca Python de código abierto que se utiliza en casi todos los campos de la ciencia y la ingeniería.

Es el estándar universal para trabajar con datos numéricos en Python y está en el centro de los ecosistemas científicos de Python y PyData.

In [27]:
# Importar la librería numpy
import numpy as np

In [28]:
# Creación de un array de floats
floats = np.array([1.1, 2.2, 3.3, 4.4, 5.5])

In [29]:
# Acceder a un elemento por su índice
print(floats[0])  # Imprime: 1.1

1.1


In [30]:
# Modificar un elemento por su índice
floats[1] = 20.2
print(floats)  # Imprime: [ 1.1 20.2 3.3 4.4 5.5]

[ 1.1 20.2  3.3  4.4  5.5]


In [31]:
# Longitud del array
print(len(floats))  # Imprime: 5

5


##Matrices

Para matrices, podemos usar la biblioteca NumPy.

Aquí hay algunos métodos integrados que se pueden usar en matrices:

In [33]:
# Importar la biblioteca NumPy
import numpy as np

In [32]:
# Crear una matriz
mi_matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [34]:
# Imprimir la matriz
print(mi_matriz)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [35]:
# Acceder al elemento en la fila 1, columna 2
print(mi_matriz[1, 2])  # Imprime: 6

6


In [36]:
# Modificar el elemento en la fila 1, columna 2
mi_matriz[1, 2] = 20
print(mi_matriz)  # Imprime: [[ 1  2  3] [ 4 20  6] [ 7  8  9]]

[[ 1  2  3]
 [ 4  5 20]
 [ 7  8  9]]


In [37]:
# Obtener el número de filas y columnas de la matriz
print(mi_matriz.shape)  # Imprime: (3, 3)

(3, 3)


In [38]:
# Sumar todos los elementos de la matriz
print(np.sum(mi_matriz))  # Imprime: 45

59


In [39]:
# Encontrar el máximo y el mínimo de los elementos de la matriz
print(np.max(mi_matriz))  # Imprime: 20
print(np.min(mi_matriz))  # Imprime: 1

20
1


In [40]:
# Ordenar los elementos de la matriz
mi_matriz_ordenada = np.sort(mi_matriz)
print(mi_matriz_ordenada)

[[ 1  2  3]
 [ 4  5 20]
 [ 7  8  9]]


##Arreglos Multidimensionales

Para trabajar con arreglos multidimensionales en Python, se puede utilizar la biblioteca NumPy.


A continuación, se presentan algunos ejemplos de código en Python que muestran cómo crear y manipular arreglos multidimensionales usando NumPy.

In [ ]:
# ya se importa anteriormente
# solo para fines ilustrativos
import numpy as np

In [41]:
# Crear un arreglo bidimensional de enteros
mi_arreglo = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [ ]:
# Imprimir el arreglo
print(mi_arreglo)

In [43]:
# Acceder al elemento en la posición (1, 1)
print(mi_arreglo[1, 1])  # Imprime: 5

5


In [44]:
# Modificar el elemento en la posición (1, 1)
mi_arreglo[1, 1] = 10
print(mi_arreglo)
# Imprime:
#   [[ 1,  2,  3],
#    [ 4, 10,  6],
#    [ 7,  8,  9]]

[[ 1  2  3]
 [ 4 10  6]
 [ 7  8  9]]


In [45]:
# Obtener el número de dimensiones del arreglo
print(mi_arreglo.ndim)  # Imprime: 2

2


In [46]:
# Obtener el tamaño del arreglo
print(mi_arreglo.size)  # Imprime: 9

9


In [47]:
# Obtener el tamaño de cada dimensión del arreglo
print(mi_arreglo.shape)  # Imprime: (3, 3)

(3, 3)


In [48]:
# Sumar todos los elementos del arreglo
print(np.sum(mi_arreglo))  # Imprime: 45

50


In [49]:
# Encontrar el máximo y el mínimo de los elementos del arreglo
print(np.max(mi_arreglo))  # Imprime: 10
print(np.min(mi_arreglo))  # Imprime: 1

10
1


In [50]:
# Ordenar los elementos del arreglo
mi_arreglo_ordenado = np.sort(mi_arreglo, axis=None)
print(mi_arreglo_ordenado)

[ 1  2  3  4  6  7  8  9 10]


In [55]:
# Crear un arreglo tridimensional de ceros
mi_arreglo_ceros = np.zeros((2, 3, 4))

# Imprimir el arreglo
print(mi_arreglo_ceros)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [56]:
# Crear un arreglo tridimensional de unos
mi_arreglo_unos = np.ones((2, 3, 4))

# Imprimir el arreglo
print(mi_arreglo_unos)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [62]:
# Crear un arreglo bidimensional con una secuencia de enteros
mi_arreglo_secuencia = np.arange(1, 13).reshape(3, 4)

# Imprimir el arreglo
print(mi_arreglo_secuencia)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
